name: "DEPLOY-BETA"

on:
  push:
    branches: ["develop"]
    paths:
      - "apps/root/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter=root build --mode=beta
        env:
          VITE_API_URL: https://api.veille.safecoffi.app
          VITE_ENV: beta

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_VEILLE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/root
          command: pages deploy apps/root/dist --project-name=veille-safecoffi-beta
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
