name: "DEPLOY-BETA"

on:
  workflow_run:
    workflows: ["CI"]
    types: ["completed"]
    branches: ["develop"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter=root build --mode=beta
        env:
          VITE_API_URL: https://api.veille.safecoffi.app
          VITE_ENV: beta

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_VEILLE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/root
          command: pages deploy dist --project-name=veille-safecoffi-beta
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
